// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (name, email)
VALUES ($1, $2)
RETURNING id, name, email, created_at
`

type CreateContactParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact, arg.Name, arg.Email)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const getContact = `-- name: GetContact :one
SELECT id, name, email, created_at FROM contacts WHERE id = $1
`

func (q *Queries) GetContact(ctx context.Context, id int32) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many

SELECT id, name, email, created_at FROM contacts ORDER BY created_at DESC
`

// ex01/db/queries/contacts.sql
//
// Anotações sqlc:
//
//	:many → SELECT que retorna 0..N linhas → ([]Contact, error)
//	:one  → SELECT/INSERT/UPDATE com RETURNING que retorna 1 linha → (Contact, error)
//	:exec → DELETE/UPDATE sem retorno → error
//
// Cada bloco abaixo gera UMA função no Go. O nome após "name:" vira o nome
// do método em internal/db/contacts.sql.go. Os "$1", "$2" são placeholders
// posicionais do PostgreSQL — sqlc gera parâmetros tipados a partir deles.
func (q *Queries) ListContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
