// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Phone struct {
	ID        int32              `json:"id"`
	ContactID int32              `json:"contact_id"`
	Label     string             `json:"label"`
	Number    string             `json:"number"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
